/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.apache.gora.orientdb.storage.test;  
@SuppressWarnings("all")
public class Edge extends org.apache.gora.persistency.impl.PersistentBase implements org.apache.avro.specific.SpecificRecord, org.apache.gora.persistency.Persistent {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Edge\",\"namespace\":\"org.apache.gora.orientdb.storage.test\",\"fields\":[{\"name\":\"__g__dirty\",\"type\":\"bytes\",\"doc\":\"Bytes used to represent weather or not a field is dirty.\",\"default\":\"AA==\"},{\"name\":\"label\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"target\",\"type\":[{\"type\":\"record\",\"name\":\"Test\",\"fields\":[{\"name\":\"__g__dirty\",\"type\":\"bytes\",\"doc\":\"Bytes used to represent weather or not a field is dirty.\",\"default\":\"AA==\"},{\"name\":\"value\",\"type\":\"int\",\"default\":0},{\"name\":\"edges\",\"type\":[{\"type\":\"array\",\"items\":\"Edge\"},\"null\"],\"default\":\"null\"}]},\"null\"],\"default\":\"null\"}]}");

  public int getFieldsCount(){
      return 2;
  }
  /** Enum containing all data bean's fields. */
  public static enum Field {
    __G__DIRTY(0, "__g__dirty"),
    LABEL(1, "label"),
    TARGET(2, "target"),
    ;
    /**
     * Field's index.
     */
    private int index;

    /**
     * Field's name.
     */
    private String name;

    /**
     * Field's constructor
     * @param index field's index.
     * @param name field's name.
     */
    Field(int index, String name) {this.index=index;this.name=name;}

    /**
     * Gets field's index.
     * @return int field's index.
     */
    public int getIndex() {return index;}

    /**
     * Gets field's name.
     * @return String field's name.
     */
    public String getName() {return name;}

    /**
     * Gets field's attributes to string.
     * @return String field's attributes to string.
     */
    public String toString() {return name;}
  };

  public static final String[] _ALL_FIELDS = {
  "__g__dirty",
  "label",
  "target",
  };

  /** Bytes used to represent weather or not a field is dirty. */
  private java.nio.ByteBuffer __g__dirty = java.nio.ByteBuffer.wrap(new byte[1]);
  private java.lang.CharSequence label;
  private org.apache.gora.orientdb.storage.test.Test target;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return __g__dirty;
    case 1: return label;
    case 2: return target;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value) {
    switch (field$) {
    case 0: __g__dirty = (java.nio.ByteBuffer)(value); break;
    case 1: label = (java.lang.CharSequence)(value); break;
    case 2: target = (org.apache.gora.orientdb.storage.test.Test)(value); break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'label' field.
   */
  public java.lang.CharSequence getLabel() {
    return label;
  }

  /**
   * Sets the value of the 'label' field.
   * @param value the value to set.
   */
  public void setLabel(java.lang.CharSequence value) {
    this.label = value;
    setDirty(1);
  }
  
  /**
   * Checks the dirty status of the 'label' field. A field is dirty if it represents a change that has not yet been written to the database.
   * @param value the value to set.
   */
  public boolean isLabelDirty(java.lang.CharSequence value) {
    return isDirty(1);
  }

  /**
   * Gets the value of the 'target' field.
   */
  public org.apache.gora.orientdb.storage.test.Test getTarget() {
    return target;
  }

  /**
   * Sets the value of the 'target' field.
   * @param value the value to set.
   */
  public void setTarget(org.apache.gora.orientdb.storage.test.Test value) {
    this.target = value;
    setDirty(2);
  }
  
  /**
   * Checks the dirty status of the 'target' field. A field is dirty if it represents a change that has not yet been written to the database.
   * @param value the value to set.
   */
  public boolean isTargetDirty(org.apache.gora.orientdb.storage.test.Test value) {
    return isDirty(2);
  }

  /** Creates a new Edge RecordBuilder */
  public static org.apache.gora.orientdb.storage.test.Edge.Builder newBuilder() {
    return new org.apache.gora.orientdb.storage.test.Edge.Builder();
  }
  
  /** Creates a new Edge RecordBuilder by copying an existing Builder */
  public static org.apache.gora.orientdb.storage.test.Edge.Builder newBuilder(org.apache.gora.orientdb.storage.test.Edge.Builder other) {
    return new org.apache.gora.orientdb.storage.test.Edge.Builder(other);
  }
  
  /** Creates a new Edge RecordBuilder by copying an existing Edge instance */
  public static org.apache.gora.orientdb.storage.test.Edge.Builder newBuilder(org.apache.gora.orientdb.storage.test.Edge other) {
    return new org.apache.gora.orientdb.storage.test.Edge.Builder(other);
  }
  
  private static java.nio.ByteBuffer deepCopyToWriteOnlyBuffer(
      java.nio.ByteBuffer input) {
    java.nio.ByteBuffer copy = java.nio.ByteBuffer.allocate(input.capacity());
    int position = input.position();
    input.reset();
    int mark = input.position();
    int limit = input.limit();
    input.rewind();
    input.limit(input.capacity());
    copy.put(input);
    input.rewind();
    copy.rewind();
    input.position(mark);
    input.mark();
    copy.position(mark);
    copy.mark();
    input.position(position);
    copy.position(position);
    input.limit(limit);
    copy.limit(limit);
    return copy.asReadOnlyBuffer();
  }
  
  /**
   * RecordBuilder for Edge instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Edge>
    implements org.apache.avro.data.RecordBuilder<Edge> {

    private java.nio.ByteBuffer __g__dirty;
    private java.lang.CharSequence label;
    private org.apache.gora.orientdb.storage.test.Test target;

    /** Creates a new Builder */
    private Builder() {
      super(org.apache.gora.orientdb.storage.test.Edge.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.apache.gora.orientdb.storage.test.Edge.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Edge instance */
    private Builder(org.apache.gora.orientdb.storage.test.Edge other) {
            super(org.apache.gora.orientdb.storage.test.Edge.SCHEMA$);
      if (isValidValue(fields()[0], other.__g__dirty)) {
        this.__g__dirty = (java.nio.ByteBuffer) data().deepCopy(fields()[0].schema(), other.__g__dirty);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.label)) {
        this.label = (java.lang.CharSequence) data().deepCopy(fields()[1].schema(), other.label);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.target)) {
        this.target = (org.apache.gora.orientdb.storage.test.Test) data().deepCopy(fields()[2].schema(), other.target);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'label' field */
    public java.lang.CharSequence getLabel() {
      return label;
    }
    
    /** Sets the value of the 'label' field */
    public org.apache.gora.orientdb.storage.test.Edge.Builder setLabel(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.label = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'label' field has been set */
    public boolean hasLabel() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'label' field */
    public org.apache.gora.orientdb.storage.test.Edge.Builder clearLabel() {
      label = null;
      fieldSetFlags()[1] = false;
      return this;
    }
    
    /** Gets the value of the 'target' field */
    public org.apache.gora.orientdb.storage.test.Test getTarget() {
      return target;
    }
    
    /** Sets the value of the 'target' field */
    public org.apache.gora.orientdb.storage.test.Edge.Builder setTarget(org.apache.gora.orientdb.storage.test.Test value) {
      validate(fields()[2], value);
      this.target = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'target' field has been set */
    public boolean hasTarget() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'target' field */
    public org.apache.gora.orientdb.storage.test.Edge.Builder clearTarget() {
      target = null;
      fieldSetFlags()[2] = false;
      return this;
    }
    
    @Override
    public Edge build() {
      try {
        Edge record = new Edge();
        record.__g__dirty = fieldSetFlags()[0] ? this.__g__dirty : (java.nio.ByteBuffer) java.nio.ByteBuffer.wrap(new byte[1]);
        record.label = fieldSetFlags()[1] ? this.label : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.target = fieldSetFlags()[2] ? this.target : (org.apache.gora.orientdb.storage.test.Test) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
  
  public Edge.Tombstone getTombstone(){
  	return TOMBSTONE;
  }

  public Edge newInstance(){
    return newBuilder().build();
  }

  private static final Tombstone TOMBSTONE = new Tombstone();
  
  public static final class Tombstone extends Edge implements org.apache.gora.persistency.Tombstone {
  
      private Tombstone() { }
  
	  				  /**
	   * Gets the value of the 'label' field.
		   */
	  public java.lang.CharSequence getLabel() {
	    throw new java.lang.UnsupportedOperationException("Get is not supported on tombstones");
	  }
	
	  /**
	   * Sets the value of the 'label' field.
		   * @param value the value to set.
	   */
	  public void setLabel(java.lang.CharSequence value) {
	    throw new java.lang.UnsupportedOperationException("Set is not supported on tombstones");
	  }
	  
	  /**
	   * Checks the dirty status of the 'label' field. A field is dirty if it represents a change that has not yet been written to the database.
		   * @param value the value to set.
	   */
	  public boolean isLabelDirty(java.lang.CharSequence value) {
	    throw new java.lang.UnsupportedOperationException("IsDirty is not supported on tombstones");
	  }
	
				  /**
	   * Gets the value of the 'target' field.
		   */
	  public org.apache.gora.orientdb.storage.test.Test getTarget() {
	    throw new java.lang.UnsupportedOperationException("Get is not supported on tombstones");
	  }
	
	  /**
	   * Sets the value of the 'target' field.
		   * @param value the value to set.
	   */
	  public void setTarget(org.apache.gora.orientdb.storage.test.Test value) {
	    throw new java.lang.UnsupportedOperationException("Set is not supported on tombstones");
	  }
	  
	  /**
	   * Checks the dirty status of the 'target' field. A field is dirty if it represents a change that has not yet been written to the database.
		   * @param value the value to set.
	   */
	  public boolean isTargetDirty(org.apache.gora.orientdb.storage.test.Test value) {
	    throw new java.lang.UnsupportedOperationException("IsDirty is not supported on tombstones");
	  }
	
		  
  }
  
}