/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.apache.gora.orientdb.storage.test;  
@SuppressWarnings("all")
public class Test extends org.apache.gora.persistency.impl.PersistentBase implements org.apache.avro.specific.SpecificRecord, org.apache.gora.persistency.Persistent {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Test\",\"namespace\":\"org.apache.gora.orientdb.storage.test\",\"fields\":[{\"name\":\"__g__dirty\",\"type\":\"bytes\",\"doc\":\"Bytes used to represent weather or not a field is dirty.\",\"default\":\"AA==\"},{\"name\":\"value\",\"type\":\"int\",\"default\":0},{\"name\":\"edges\",\"type\":[{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Edge\",\"fields\":[{\"name\":\"__g__dirty\",\"type\":\"bytes\",\"doc\":\"Bytes used to represent weather or not a field is dirty.\",\"default\":\"AA==\"},{\"name\":\"label\",\"type\":[\"string\",\"null\"],\"default\":\"null\"},{\"name\":\"target\",\"type\":[\"Test\",\"null\"],\"default\":\"null\"}]}},\"null\"],\"default\":\"null\"}]}");

  public int getFieldsCount(){
      return 2;
  }
  /** Enum containing all data bean's fields. */
  public static enum Field {
    __G__DIRTY(0, "__g__dirty"),
    VALUE(1, "value"),
    EDGES(2, "edges"),
    ;
    /**
     * Field's index.
     */
    private int index;

    /**
     * Field's name.
     */
    private String name;

    /**
     * Field's constructor
     * @param index field's index.
     * @param name field's name.
     */
    Field(int index, String name) {this.index=index;this.name=name;}

    /**
     * Gets field's index.
     * @return int field's index.
     */
    public int getIndex() {return index;}

    /**
     * Gets field's name.
     * @return String field's name.
     */
    public String getName() {return name;}

    /**
     * Gets field's attributes to string.
     * @return String field's attributes to string.
     */
    public String toString() {return name;}
  };

  public static final String[] _ALL_FIELDS = {
  "__g__dirty",
  "value",
  "edges",
  };

  /** Bytes used to represent weather or not a field is dirty. */
  private java.nio.ByteBuffer __g__dirty = java.nio.ByteBuffer.wrap(new byte[1]);
  private int value;
  private java.util.List<org.apache.gora.orientdb.storage.test.Edge> edges;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return __g__dirty;
    case 1: return value;
    case 2: return edges;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value) {
    switch (field$) {
    case 0: __g__dirty = (java.nio.ByteBuffer)(value); break;
    case 1: value = (java.lang.Integer)(value); break;
    case 2: edges = (java.util.List<org.apache.gora.orientdb.storage.test.Edge>)(value); break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'value' field.
   */
  public java.lang.Integer getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.Integer value) {
    this.value = value;
    setDirty(1);
  }
  
  /**
   * Checks the dirty status of the 'value' field. A field is dirty if it represents a change that has not yet been written to the database.
   * @param value the value to set.
   */
  public boolean isValueDirty(java.lang.Integer value) {
    return isDirty(1);
  }

  /**
   * Gets the value of the 'edges' field.
   */
  public java.util.List<org.apache.gora.orientdb.storage.test.Edge> getEdges() {
    return edges;
  }

  /**
   * Sets the value of the 'edges' field.
   * @param value the value to set.
   */
  public void setEdges(java.util.List<org.apache.gora.orientdb.storage.test.Edge> value) {
    this.edges = value;
    setDirty(2);
  }
  
  /**
   * Checks the dirty status of the 'edges' field. A field is dirty if it represents a change that has not yet been written to the database.
   * @param value the value to set.
   */
  public boolean isEdgesDirty(java.util.List<org.apache.gora.orientdb.storage.test.Edge> value) {
    return isDirty(2);
  }

  /** Creates a new Test RecordBuilder */
  public static org.apache.gora.orientdb.storage.test.Test.Builder newBuilder() {
    return new org.apache.gora.orientdb.storage.test.Test.Builder();
  }
  
  /** Creates a new Test RecordBuilder by copying an existing Builder */
  public static org.apache.gora.orientdb.storage.test.Test.Builder newBuilder(org.apache.gora.orientdb.storage.test.Test.Builder other) {
    return new org.apache.gora.orientdb.storage.test.Test.Builder(other);
  }
  
  /** Creates a new Test RecordBuilder by copying an existing Test instance */
  public static org.apache.gora.orientdb.storage.test.Test.Builder newBuilder(org.apache.gora.orientdb.storage.test.Test other) {
    return new org.apache.gora.orientdb.storage.test.Test.Builder(other);
  }
  
  private static java.nio.ByteBuffer deepCopyToWriteOnlyBuffer(
      java.nio.ByteBuffer input) {
    java.nio.ByteBuffer copy = java.nio.ByteBuffer.allocate(input.capacity());
    int position = input.position();
    input.reset();
    int mark = input.position();
    int limit = input.limit();
    input.rewind();
    input.limit(input.capacity());
    copy.put(input);
    input.rewind();
    copy.rewind();
    input.position(mark);
    input.mark();
    copy.position(mark);
    copy.mark();
    input.position(position);
    copy.position(position);
    input.limit(limit);
    copy.limit(limit);
    return copy.asReadOnlyBuffer();
  }
  
  /**
   * RecordBuilder for Test instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Test>
    implements org.apache.avro.data.RecordBuilder<Test> {

    private java.nio.ByteBuffer __g__dirty;
    private int value;
    private java.util.List<org.apache.gora.orientdb.storage.test.Edge> edges;

    /** Creates a new Builder */
    private Builder() {
      super(org.apache.gora.orientdb.storage.test.Test.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.apache.gora.orientdb.storage.test.Test.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Test instance */
    private Builder(org.apache.gora.orientdb.storage.test.Test other) {
            super(org.apache.gora.orientdb.storage.test.Test.SCHEMA$);
      if (isValidValue(fields()[0], other.__g__dirty)) {
        this.__g__dirty = (java.nio.ByteBuffer) data().deepCopy(fields()[0].schema(), other.__g__dirty);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.value)) {
        this.value = (java.lang.Integer) data().deepCopy(fields()[1].schema(), other.value);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.edges)) {
        this.edges = (java.util.List<org.apache.gora.orientdb.storage.test.Edge>) data().deepCopy(fields()[2].schema(), other.edges);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'value' field */
    public java.lang.Integer getValue() {
      return value;
    }
    
    /** Sets the value of the 'value' field */
    public org.apache.gora.orientdb.storage.test.Test.Builder setValue(int value) {
      validate(fields()[1], value);
      this.value = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'value' field has been set */
    public boolean hasValue() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'value' field */
    public org.apache.gora.orientdb.storage.test.Test.Builder clearValue() {
      fieldSetFlags()[1] = false;
      return this;
    }
    
    /** Gets the value of the 'edges' field */
    public java.util.List<org.apache.gora.orientdb.storage.test.Edge> getEdges() {
      return edges;
    }
    
    /** Sets the value of the 'edges' field */
    public org.apache.gora.orientdb.storage.test.Test.Builder setEdges(java.util.List<org.apache.gora.orientdb.storage.test.Edge> value) {
      validate(fields()[2], value);
      this.edges = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'edges' field has been set */
    public boolean hasEdges() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'edges' field */
    public org.apache.gora.orientdb.storage.test.Test.Builder clearEdges() {
      edges = null;
      fieldSetFlags()[2] = false;
      return this;
    }
    
    @Override
    public Test build() {
      try {
        Test record = new Test();
        record.__g__dirty = fieldSetFlags()[0] ? this.__g__dirty : (java.nio.ByteBuffer) java.nio.ByteBuffer.wrap(new byte[1]);
        record.value = fieldSetFlags()[1] ? this.value : (java.lang.Integer) defaultValue(fields()[1]);
        record.edges = fieldSetFlags()[2] ? this.edges : (java.util.List<org.apache.gora.orientdb.storage.test.Edge>) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
  
  public Test.Tombstone getTombstone(){
  	return TOMBSTONE;
  }

  public Test newInstance(){
    return newBuilder().build();
  }

  private static final Tombstone TOMBSTONE = new Tombstone();
  
  public static final class Tombstone extends Test implements org.apache.gora.persistency.Tombstone {
  
      private Tombstone() { }
  
	  				  /**
	   * Gets the value of the 'value' field.
		   */
	  public java.lang.Integer getValue() {
	    throw new java.lang.UnsupportedOperationException("Get is not supported on tombstones");
	  }
	
	  /**
	   * Sets the value of the 'value' field.
		   * @param value the value to set.
	   */
	  public void setValue(java.lang.Integer value) {
	    throw new java.lang.UnsupportedOperationException("Set is not supported on tombstones");
	  }
	  
	  /**
	   * Checks the dirty status of the 'value' field. A field is dirty if it represents a change that has not yet been written to the database.
		   * @param value the value to set.
	   */
	  public boolean isValueDirty(java.lang.Integer value) {
	    throw new java.lang.UnsupportedOperationException("IsDirty is not supported on tombstones");
	  }
	
				  /**
	   * Gets the value of the 'edges' field.
		   */
	  public java.util.List<org.apache.gora.orientdb.storage.test.Edge> getEdges() {
	    throw new java.lang.UnsupportedOperationException("Get is not supported on tombstones");
	  }
	
	  /**
	   * Sets the value of the 'edges' field.
		   * @param value the value to set.
	   */
	  public void setEdges(java.util.List<org.apache.gora.orientdb.storage.test.Edge> value) {
	    throw new java.lang.UnsupportedOperationException("Set is not supported on tombstones");
	  }
	  
	  /**
	   * Checks the dirty status of the 'edges' field. A field is dirty if it represents a change that has not yet been written to the database.
		   * @param value the value to set.
	   */
	  public boolean isEdgesDirty(java.util.List<org.apache.gora.orientdb.storage.test.Edge> value) {
	    throw new java.lang.UnsupportedOperationException("IsDirty is not supported on tombstones");
	  }
	
		  
  }
  
}