/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.phinence.spark.storage;  
@SuppressWarnings("all")
public class EdgeComp extends org.apache.gora.persistency.impl.PersistentBase implements org.apache.avro.specific.SpecificRecord, org.apache.gora.persistency.Persistent {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EdgeComp\",\"namespace\":\"com.phinence.spark.storage\",\"fields\":[{\"name\":\"__g__dirty\",\"type\":\"bytes\",\"doc\":\"Bytes used to represent weather or not a field is dirty.\",\"default\":\"AA==\"},{\"name\":\"label\",\"type\":[\"string\",\"null\"]},{\"name\":\"target\",\"type\":[{\"type\":\"record\",\"name\":\"Ohlc\",\"fields\":[{\"name\":\"__g__dirty\",\"type\":\"bytes\",\"doc\":\"Bytes used to represent weather or not a field is dirty.\",\"default\":\"AA==\"},{\"name\":\"Open\",\"type\":\"float\",\"default\":0.0},{\"name\":\"High\",\"type\":\"float\",\"default\":0.0},{\"name\":\"Low\",\"type\":\"float\",\"default\":0.0},{\"name\":\"Close\",\"type\":\"float\",\"default\":0.0},{\"name\":\"Volume\",\"type\":\"long\",\"default\":0}]},\"null\"]}]}");
public int getFieldsCount(){
      return 2;
  }
  /** Enum containing all data bean's fields. */
  public static enum Field {
    __G__DIRTY(0, "__g__dirty"),
    LABEL(1, "label"),
    TARGET(2, "target"),
    ;
    /**
     * Field's index.
     */
    private int index;

    /**
     * Field's name.
     */
    private String name;

    /**
     * Field's constructor
     * @param index field's index.
     * @param name field's name.
     */
    Field(int index, String name) {this.index=index;this.name=name;}

    /**
     * Gets field's index.
     * @return int field's index.
     */
    public int getIndex() {return index;}

    /**
     * Gets field's name.
     * @return String field's name.
     */
    public String getName() {return name;}

    /**
     * Gets field's attributes to string.
     * @return String field's attributes to string.
     */
    public String toString() {return name;}
  };

  public static final String[] _ALL_FIELDS = {
  "__g__dirty",
  "label",
  "target",
  };

  /** Bytes used to represent weather or not a field is dirty. */
  private java.nio.ByteBuffer __g__dirty = java.nio.ByteBuffer.wrap(new byte[1]);
  private java.lang.CharSequence label;
  private com.phinence.spark.storage.Ohlc target;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return __g__dirty;
    case 1: return label;
    case 2: return target;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value) {
    switch (field$) {
    case 0: __g__dirty = (java.nio.ByteBuffer)(value); break;
    case 1: label = (java.lang.CharSequence)(value); break;
    case 2: target = (com.phinence.spark.storage.Ohlc)(value); break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'label' field.
   */
  public java.lang.CharSequence getLabel() {
    return label;
  }

  /**
   * Sets the value of the 'label' field.
   * @param value the value to set.
   */
  public void setLabel(java.lang.CharSequence value) {
    this.label = value;
    setDirty(1);
  }
  
  /**
   * Checks the dirty status of the 'label' field. A field is dirty if it represents a change that has not yet been written to the database.
   * @param value the value to set.
   */
  public boolean isLabelDirty(java.lang.CharSequence value) {
    return isDirty(1);
  }

  /**
   * Gets the value of the 'target' field.
   */
  public com.phinence.spark.storage.Ohlc getTarget() {
    return target;
  }

  /**
   * Sets the value of the 'target' field.
   * @param value the value to set.
   */
  public void setTarget(com.phinence.spark.storage.Ohlc value) {
    this.target = value;
    setDirty(2);
  }
  
  /**
   * Checks the dirty status of the 'target' field. A field is dirty if it represents a change that has not yet been written to the database.
   * @param value the value to set.
   */
  public boolean isTargetDirty(com.phinence.spark.storage.Ohlc value) {
    return isDirty(2);
  }

  /** Creates a new EdgeComp RecordBuilder */
  public static com.phinence.spark.storage.EdgeComp.Builder newBuilder() {
    return new com.phinence.spark.storage.EdgeComp.Builder();
  }
  
  /** Creates a new EdgeComp RecordBuilder by copying an existing Builder */
  public static com.phinence.spark.storage.EdgeComp.Builder newBuilder(com.phinence.spark.storage.EdgeComp.Builder other) {
    return new com.phinence.spark.storage.EdgeComp.Builder(other);
  }
  
  /** Creates a new EdgeComp RecordBuilder by copying an existing EdgeComp instance */
  public static com.phinence.spark.storage.EdgeComp.Builder newBuilder(com.phinence.spark.storage.EdgeComp other) {
    return new com.phinence.spark.storage.EdgeComp.Builder(other);
  }
  
  private static java.nio.ByteBuffer deepCopyToWriteOnlyBuffer(
      java.nio.ByteBuffer input) {
    java.nio.ByteBuffer copy = java.nio.ByteBuffer.allocate(input.capacity());
    int position = input.position();
    input.reset();
    int mark = input.position();
    int limit = input.limit();
    input.rewind();
    input.limit(input.capacity());
    copy.put(input);
    input.rewind();
    copy.rewind();
    input.position(mark);
    input.mark();
    copy.position(mark);
    copy.mark();
    input.position(position);
    copy.position(position);
    input.limit(limit);
    copy.limit(limit);
    return copy.asReadOnlyBuffer();
  }
  
  /**
   * RecordBuilder for EdgeComp instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EdgeComp>
    implements org.apache.avro.data.RecordBuilder<EdgeComp> {

    private java.nio.ByteBuffer __g__dirty;
    private java.lang.CharSequence label;
    private com.phinence.spark.storage.Ohlc target;

    /** Creates a new Builder */
    private Builder() {
      super(com.phinence.spark.storage.EdgeComp.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.phinence.spark.storage.EdgeComp.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing EdgeComp instance */
    private Builder(com.phinence.spark.storage.EdgeComp other) {
            super(com.phinence.spark.storage.EdgeComp.SCHEMA$);
      if (isValidValue(fields()[0], other.__g__dirty)) {
        this.__g__dirty = (java.nio.ByteBuffer) data().deepCopy(fields()[0].schema(), other.__g__dirty);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.label)) {
        this.label = (java.lang.CharSequence) data().deepCopy(fields()[1].schema(), other.label);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.target)) {
        this.target = (com.phinence.spark.storage.Ohlc) data().deepCopy(fields()[2].schema(), other.target);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'label' field */
    public java.lang.CharSequence getLabel() {
      return label;
    }
    
    /** Sets the value of the 'label' field */
    public com.phinence.spark.storage.EdgeComp.Builder setLabel(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.label = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'label' field has been set */
    public boolean hasLabel() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'label' field */
    public com.phinence.spark.storage.EdgeComp.Builder clearLabel() {
      label = null;
      fieldSetFlags()[1] = false;
      return this;
    }
    
    /** Gets the value of the 'target' field */
    public com.phinence.spark.storage.Ohlc getTarget() {
      return target;
    }
    
    /** Sets the value of the 'target' field */
    public com.phinence.spark.storage.EdgeComp.Builder setTarget(com.phinence.spark.storage.Ohlc value) {
      validate(fields()[2], value);
      this.target = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'target' field has been set */
    public boolean hasTarget() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'target' field */
    public com.phinence.spark.storage.EdgeComp.Builder clearTarget() {
      target = null;
      fieldSetFlags()[2] = false;
      return this;
    }
    
    @Override
    public EdgeComp build() {
      try {
        EdgeComp record = new EdgeComp();
        record.__g__dirty = fieldSetFlags()[0] ? this.__g__dirty : (java.nio.ByteBuffer) java.nio.ByteBuffer.wrap(new byte[1]);
        record.label = fieldSetFlags()[1] ? this.label : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.target = fieldSetFlags()[2] ? this.target : (com.phinence.spark.storage.Ohlc) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
  
  public EdgeComp.Tombstone getTombstone(){
  	return TOMBSTONE;
  }

  public EdgeComp newInstance(){
    return newBuilder().build();
  }

  private static final Tombstone TOMBSTONE = new Tombstone();
  
  public static final class Tombstone extends EdgeComp implements org.apache.gora.persistency.Tombstone {
  
      private Tombstone() { }
  
	  				  /**
	   * Gets the value of the 'label' field.
		   */
	  public java.lang.CharSequence getLabel() {
	    throw new java.lang.UnsupportedOperationException("Get is not supported on tombstones");
	  }
	
	  /**
	   * Sets the value of the 'label' field.
		   * @param value the value to set.
	   */
	  public void setLabel(java.lang.CharSequence value) {
	    throw new java.lang.UnsupportedOperationException("Set is not supported on tombstones");
	  }
	  
	  /**
	   * Checks the dirty status of the 'label' field. A field is dirty if it represents a change that has not yet been written to the database.
		   * @param value the value to set.
	   */
	  public boolean isLabelDirty(java.lang.CharSequence value) {
	    throw new java.lang.UnsupportedOperationException("IsDirty is not supported on tombstones");
	  }
	
				  /**
	   * Gets the value of the 'target' field.
		   */
	  public com.phinence.spark.storage.Ohlc getTarget() {
	    throw new java.lang.UnsupportedOperationException("Get is not supported on tombstones");
	  }
	
	  /**
	   * Sets the value of the 'target' field.
		   * @param value the value to set.
	   */
	  public void setTarget(com.phinence.spark.storage.Ohlc value) {
	    throw new java.lang.UnsupportedOperationException("Set is not supported on tombstones");
	  }
	  
	  /**
	   * Checks the dirty status of the 'target' field. A field is dirty if it represents a change that has not yet been written to the database.
		   * @param value the value to set.
	   */
	  public boolean isTargetDirty(com.phinence.spark.storage.Ohlc value) {
	    throw new java.lang.UnsupportedOperationException("IsDirty is not supported on tombstones");
	  }
	
		  
  }
  
}